### ISSUE TITLE
MMC not loading in 2.2.0.18

### ISSUE THREAD

**Issue by k-korn** [neos-sdi/adfsmfa#20]
OS: Windows Server 2016 ver. 1607, previously installed v. 2.0 of ADFS MFA.

Steps to reproduce:
- Run UnRegister-MFASystem
- Uninstall MFA 2.0
- Reboot
- Install 2.2.0.18

As a result, the following message appears trying to load the MMC snap-in: 
![image](https://user-images.githubusercontent.com/20152583/42530314-8dd8f484-8489-11e8-9338-9f96e1fe983f.png)

Full text below:

Could not load file or assembly 'Neos.IdentityServer.Console, Version=2.0.0.0, Culture=neutral, PublicKeyToken=175aa5ee756d2aa2' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

```
System.IO.FileLoadException
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName)
   at Microsoft.ManagementConsole.Internal.SnapInClient.CreateSnapIn(String assemblyName, String typeName)
   at Microsoft.ManagementConsole.Internal.ClassLibraryServices.Microsoft.ManagementConsole.Internal.IClassLibraryServices.CreateSnapIn(String assemblyName, String typeName)
   at Microsoft.ManagementConsole.Executive.SnapInInitializationOperation.OnStart()
   at Microsoft.ManagementConsole.Executive.RunningOperationsTable.EnqueueOperation(Operation operation)
   at Microsoft.ManagementConsole.Advanced.FrameworkSnapInFactory.Microsoft.ManagementConsole.Advanced.ISnapInFactory.CreateSnapIn(Int32 bookkeepingId, String snapInKey, Object& snapIn)

```

**Comment by redhook62** [comment]
Hi, K-Korm

If your have unregistered the configuration, the MMC snapin cannot load  it.

Same thing, for PowerShell, or the web Site.

So try to run Register-MFASystem.

And After run Import-MFASystemConfiguration  with your saved config file

Regards

**Comment by anorstrom** [comment]
I run into the same issue in one of our LAB domains. (First domain where I tested the 2.2 beta, it worked fine. Then I was going to test in an other LAB domain, I did the same thing, but there I run into this problem.)

I then tried Unregister, Uninstall, Restart and then Install and Register again (tried both restoring and not restoring old config). But I keep getting this "Unhandled Exception..." too when I try to open the MMC.

`Could not load file or assembly 'Neos.IdentityServer.Console, Version=2.0.0.0, Culture=neutral, PublicKeyToken=175aa5ee756d2aa2' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

**Comment by redhook62** [comment]
Hi,

On my adfs server 2016 the MMC version is 3.0

![image](https://user-images.githubusercontent.com/26826945/42655195-94c2c1f6-861b-11e8-95d7-6894c010bfb8.png)

These servers exposed on the internet must be updated regulary with Windows Update. 

It seems, that the MMC MFA Snap is not well registered (self registration with assembly type at install for x64 and x86 registry access). I can reproduce your problems with ADFS on Windows 2012 R2 !

```As a quick workaround : 
Lauch Regedit as administrator
Select HKEY_CLASSES_ROOT
Search for : FX:{9627f1f3-a6d2-4cf8-90a2-10f85a7a4ee7}
In the right pane look at the Type attribute and modify the version with 2.2.0.0 if needed.
 ```

I think, you can Import your saved config file with Import-MFASystemConfiguration.

Surely, a security problem with OS, the new assembly not seems to register itself correctly.
I will check that this Week-end

Regards

**Comment by k-korn** [comment]
Thanks, workaround with regedit fixed the issue for  me.
