### ISSUE TITLE
2.2.0.20 - TOTP code does not work at login

### ISSUE THREAD

**Issue by anorstrom** [neos-sdi/adfsmfa#23]
Hi,
Thank you for 2.2.0.20, we like the new wizard option and the wizard works well.

But we don't get TOTP code to work in version 2.2.0.20. We can enroll the TOTP App, and also on the Code Verification page the code is confirmed successfully. But the TOTP code is not working when we try a regular login after that, it just says "An error occurred".  

Event Log logs:
```
Exception details: 
Microsoft.IdentityServer.Web.Authentication.External.ExternalAuthenticationException: user@domain.com : Object reference not set to an instance of an object.
   at Neos.IdentityServer.MultiFactor.AuthenticationProvider.TryIdentification(AuthenticationContext usercontext, IAuthenticationContext context, IProofData proofData, HttpListenerRequest request, Claim[]& claims)
   at Neos.IdentityServer.MultiFactor.AuthenticationProvider.TryEndAuthentication(IAuthenticationContext context, IProofData proofData, HttpListenerRequest request, Claim[]& claims)
   at Microsoft.IdentityServer.Web.Authentication.External.ExternalAuthenticationHandlerBase.TryEndAuthentication(IAuthenticationContext authContext, IProofData proofData, HttpListenerRequest request, Claim[]& adapterClaims)
   at Microsoft.IdentityServer.Web.Authentication.External.ExternalAuthenticationHandler.Process(ProtocolContext context)
   at Microsoft.IdentityServer.Web.Authentication.AuthenticationOptionsHandler.Process(ProtocolContext context)
   at Microsoft.IdentityServer.Web.PassiveProtocolListener.OnGetContext(WrappedHttpListenerContext context)
```

We tried to unregister and reregister MFA adapter, both with RSA and RNG. Also tried to unregister, uninstall completely and install and register again, but same issue.

Any ideas?

Thanks,
Andreas

**Comment by redhook62** [comment]
Hi,

Yes, it was a bug, new version 2.2.0.21 just for this problem.
