### ISSUE TITLE
Errors After Restarting MFA Notification Hub in adfsmfa.3.1.2306.0

### ISSUE THREAD

**Issue by Iddunx** [neos-sdi/adfsmfa#363]
Hi @redhook62,

We are using **adfsmfa.3.1.2306.0**, and from time to time, after restarting the **MFA Notification Hub**, we encounter the following issues:

#### 1. **Error Initializing WebAuthN Metadata Repository**
- **Event ID:** 2000
- **Source:** ADFS MFA Service
- **Description:**
  ```
  Error Initializing WebAuthN Metadata Repository : Failed to validate cert chain while parsing BLOB ///    at Neos.IdentityServer.MultiFactor.WebAuthN.Metadata.MDSMetadataRepository.DeserializeAndValidateBlob(BLOBPayloadInformations infos)
     at Neos.IdentityServer.MultiFactor.WebAuthN.Metadata.MDSMetadataRepository.GetBLOB()
     at Neos.IdentityServer.MultiFactor.WebAuthN.MFAMetadataService.InitializeRepository(IMetadataRepository repository)
  ```

#### 2. **Error During Authentication Process**
- **Event ID:** 802
- **Source:** ADFS MFA Service
- **Description:**
  ```
  Error during authentication process! System.IndexOutOfRangeException: Index was outside the bounds of the array.
     at System.Collections.Generic.List`1.Add(T item)
     at Neos.IdentityServer.MultiFactor.AdapterPresentation.InitPlaceHolders()
     at Neos.IdentityServer.MultiFactor.AdapterPresentation..ctor(AuthenticationProvider provider, IAuthenticationContext context)
     at Neos.IdentityServer.MultiFactor.AuthenticationProvider.BeginAuthentication(Claim identityClaim, HttpListenerRequest request, IAuthenticationContext context)!
  ```

#### 3. **ErrorAuthenticating**
- **Event ID:** 2000
- **Source:** ADFS MFA Service
- **Description:**
  ```
  ErrorAuthenticating : System.IndexOutOfRangeException: Index was outside the bounds of the array.
     at Neos.IdentityServer.MultiFactor.AuthenticationProvider.BeginAuthentication(Claim identityClaim, HttpListenerRequest request, IAuthenticationContext context)
  ```

---

### Impact

After these set of errors , the MFA service stops working (looks like it gets stuck).
Users cannot authenticate, and the 2FA code prompt no longer appears during authentication attempts.

Could you please advise on potential fixes or mitigations for these issues?

Thank you in advance!

**Regards,**
@iddunx

**Comment by redhook62** [comment]
Hi, @Iddunx 

You should upgrade to the latest version : 3.1.2411.0
The error comes from the size of the metadata retrieved from the fido alliance which seems too large for Microsoft components (Packages).

regards
