### ISSUE TITLE
Hash algorithm set to SHAxxx other than SHA1 not work

### ISSUE THREAD

**Issue by unchannam** [neos-sdi/adfsmfa#7]
I try to set SHA256, security mode set to RNG 1024bits, regenerate the user's key and use Google authenticator/Microsoft authenticator to generate OTP. But it cannot login and the exception is as below. So my question is can I use SHAxxx other than SHA1? Thanks.

![image](https://user-images.githubusercontent.com/14857241/34549145-6a83882c-f141-11e7-82c1-448b65200d39.png)

Encountered error during federation passive request. 

Additional Data 

Protocol Name: 
OAuthAuthorizationProtocol 

Relying Party: 
https://fs.adfsuat.local 

Exception details: 
Microsoft.IdentityServer.Web.Authentication.External.ExternalAuthenticationException: user@adfsuat.local : Invalid identification, please restart your session.
   at Neos.IdentityServer.MultiFactor.AuthenticationProvider.TryLocking(AuthenticationContext usercontext, IAuthenticationContext context, IProofData proofData, HttpListenerRequest request, Claim[]& claims)
   at Neos.IdentityServer.MultiFactor.AuthenticationProvider.TryEndAuthentication(IAuthenticationContext context, IProofData proofData, HttpListenerRequest request, Claim[]& claims)
   at Microsoft.IdentityServer.Web.Authentication.External.ExternalAuthenticationHandlerBase.TryEndAuthentication(IAuthenticationContext authContext, IProofData proofData, HttpListenerRequest request, Claim[]& adapterClaims)
   at Microsoft.IdentityServer.Web.Authentication.External.ExternalAuthenticationHandler.Process(ProtocolContext context)
   at Microsoft.IdentityServer.Web.Authentication.AuthenticationOptionsHandler.Process(ProtocolContext context)
   at Microsoft.IdentityServer.Web.PassiveProtocolListener.OnGetContext(WrappedHttpListenerContext context)

![image](https://user-images.githubusercontent.com/14857241/34548942-efd07046-f13f-11e7-976a-95214ffe58f8.png)

**Comment by redhook62** [comment]
In short, No.

But the spécifications for HOTP only supports HMAC-SHA1, for TOTP, the specifications supports (SHA1, SHA256, SHA3384, SHA512)

But, when we push your first version, Mobile Apps like Google Authenticator, Microsoft Authenticator ONLY supports SHA1. But thers's no security problem (:sunglasses:) because the code is changing every 30 seconds.

See : 
https://github.com/google/google-authenticator-libpam/issues/11
https://tools.ietf.org/html/rfc6238
https://tools.ietf.org/html/rfc4226

So we choose, to stay "compatible" with IETF and editors implementations. 

We can look again, if it is desirable to implement superior hash algorithm (aka: SHA256). 
But it must absolutely be functional with the majority of Google and Microsoft "Authenticator" mobile applications.

On the other hand, it is possible to have very complex keys, that' why we push an implementation with certificates (keys 2048 RSA)

**Comment by unchannam** [comment]
I see. I just want to know if I can use higher SHA because the algorithm textbox can be changed, now I am sure it cannot. Thanks.

**Comment by redhook62** [comment]
Of  course, we want to use higher SHA algoritm, the textbox follow the "official" (ietf !) specification.
As we said, soon, we are going to look if we we can now support SHA256 and higher.

Regards

**Comment by redhook62** [comment]
**Version 2.0.2966 available**

We added support for iterating (downgrading) HMAC algorhytms :  SHA1, SHA256 to SHA512
Remember, that it's not a bug, these algorythms are specified in rfc4226 and rfc6238. but they are not supported by many editors (Microsoft, Google, ...) To support SHA256 you must use an Authenticator like
[Authy](https://play.google.com/store/apps/details?id=com.authy.authy)  

Regards
