### ISSUE TITLE
2.4.4720.0001: Get-MFAUsers not working and other issues

### ISSUE THREAD

**Issue by pcdiks** [neos-sdi/adfsmfa#79]
We upgraded from version 2.0.2.x to version 2.4.4720.0001 because we want to start with ADFS on Windows Server 2019. Our current setup consists of two ADFS servers based on Windows Server 2016.
We used the instructions on the releases page which means:
1. Export configuration
2. Uninstall old MSI
3. Edit config file
4. Install new MSI
5. Execute the powershell commands
6. Adjusting the LibVersion back to V1

After this, everything seems to be fine. We can use MFA to logon but if we use the powershell cmdlet Get-MFAUsers we get the following error message:
```powershell
PS C:\Windows\system32> Get-MFAUsers
Get-MFAUsers : The server is not operational.
At line:1 char:1
+ Get-MFAUsers
+ ~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Get-MFAUsers], Exception
    + FullyQualifiedErrorId : 1000,Neos.IdentityServer.MultiFactor.Administration.GetMFAUser
```

Next we tried the Management Tool to get a list of users by clicking on the 'Users Management' node, that fails as well with this error message:
![error](https://user-images.githubusercontent.com/16719277/62109400-85c65f00-b2ac-11e9-8a5c-7060cec80fc5.png)
The content of the Exception stack trace is:
```
at Neos.IdentityServer.MultiFactor.Data.ADDSDataRepositoryService.GetUserRegistrations(DataFilterObject filter, DataOrderObject order, DataPagingObject paging)
   at Neos.IdentityServer.MultiFactor.RuntimeRepository.GetUserRegistrations(MFAConfig cfg, DataFilterObject filter, DataOrderObject order, DataPagingObject paging)
   at Neos.IdentityServer.MultiFactor.Administration.ManagementService.GetUserRegistrations(DataFilterObject filter, DataOrderObject order, DataPagingObject paging)
   at Neos.IdentityServer.Console.MMCService.GetUsers()
   at Neos.IdentityServer.Console.UsersListView.RefreshData(Boolean refreshgrid, Boolean clearselection)
   at Neos.IdentityServer.Console.UsersListView.OnInitialize()
   at Neos.IdentityServer.Console.UsersListView.Initialize(FormView view)
   at Microsoft.ManagementConsole.FormView.InternalInitialize()
   at Microsoft.ManagementConsole.View.HandleInitializationRequest(IRequestStatus requestStatus)
   at Microsoft.ManagementConsole.View.ProcessRequest(Request request)
   at Microsoft.ManagementConsole.ViewMessageClient.ProcessRequest(Request request)
   at Microsoft.ManagementConsole.Internal.IMessageClient.ProcessRequest(Request request)
   at Microsoft.ManagementConsole.Executive.RequestStatus.BeginRequest(IMessageClient messageClient, RequestInfo requestInfo)
   at Microsoft.ManagementConsole.Executive.SnapInRequestOperation.ProcessRequest()
   at Microsoft.ManagementConsole.Executive.Operation.OnThreadTransfer(SimpleOperationCallback callback)
```

We will roll back to version 2.0.2 to get to a working setup for now.

**Comment by redhook62** [comment]
Hi @pcdiks 

I think that the version  version 2.0.2.x is too old, and the schema seems to be not compatible with version 2;4.

The easiest way is th recreate a new configuration and update your properties manually.

Regards

**Comment by pcdiks** [comment]
Hi,

Ok but does this mean that we have to setup all users again?
Or can we keep the keys on the users and will that work again?

Thanks


Van: redhook <notifications@github.com>
Verzonden: dinsdag 30 juli 2019 19:22
Aan: neos-sdi/adfsmfa <adfsmfa@noreply.github.com>
CC: Paul-Christiaan Diks <pc@diks.org>; Mention <mention@noreply.github.com>
Onderwerp: Re: [neos-sdi/adfsmfa] 2.4.4720.0001: Get-MFAUsers not working and other issues (#79)


Hi @pcdiks<https://github.com/pcdiks>

I think that the version version 2.0.2.x is too old, and the schema seems to be not compatible with version 2;4.

The easiest way is th recreate a new configuration and update your properties manually.

Regards

**Comment by redhook62** [comment]
**No do not reset your users !!!**
We are going to check this issue.

Regards
