### ISSUE TITLE
input string was not in a correct format

### ISSUE THREAD

**Issue by w258194008** [neos-sdi/adfsmfa#89]
Hi, 
I have installed version 2.3.0.1100 on windows server 2019. Then I used Google authenticator to scan QR code in MMC and bind a test account. When I choose OTP authentication method, and enter a code from google authenticator. It will throw an error: input string was not in a correct format.

Here is the details of the log:
`Microsoft.IdentityServer.Web.Authentication.External.ExternalAuthenticationException: username@contoso.com : input string was not in a correct format
at Neos.IdentityServer.MultiFactor.AuthenticationProvider.TryIdentification(AuthenticationContext usercontext, IAuthenticationContext context, IProofData proofData, HttpListenerRequest request, Claim[]& claims)
at Neos.IdentityServer.MultiFactor.AuthenticationProvider.TryEndAuthentication(IAuthenticationContext context, IProofData proofData, HttpListenerRequest request, Claim[]& claims)
at Microsoft.IdentityServer.Web.Authentication.External.ExternalAuthenticationHandlerBase.TryEndAuthentication(IAuthenticationContext authContext, IProofData proofData, HttpListenerRequest request, Claim[]& adapterClaims)
at Microsoft.IdentityServer.Web.Authentication.External.ExternalAuthenticationHandler.Process(ProtocolContext context)
at Microsoft.IdentityServer.Web.Authentication.AuthenticationOptionsHandler.Process(ProtocolContext context)
at Microsoft.IdentityServer.Web.PassiveProtocolListener.OnGetContext(WrappedHttpListenerContext context)`
![image](https://user-images.githubusercontent.com/11494993/68544004-553ca800-03f9-11ea-8789-44c0c2744888.png)
![image](https://user-images.githubusercontent.com/11494993/68544007-6980a500-03f9-11ea-9c71-75748845ae7c.png)

I've upgraded the new version 2.4.4720.3000, but the error was still there.

Please help me! I haven't slept for a long time.

Thank You!

**Comment by redhook62** [comment]
Hi,

As you may suspect, we do not think this is a bug. especially since version 2.3...

Two things :
Do you specify the PIN code? because in your case it is asked for a TOTP code plus an additional PIN code (default pin code is 1234). 
Or otherwise disable PIN required on TOTP provider.

Then, do you have in your Relying Party's claims positioned the UPN claim: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn with a correct value. 

The problem seems to occur in the TryIdentification method, this is a generic exception

`catch (Exception ex)
{
                throw new ExternalAuthenticationException(usercontext.UPN + " : " + ex.Message, context);
}
return result;`

Please post more configuration details (ADDS/SQL, Policy Template, General paramaters and so on...)
Regards

**Comment by w258194008** [comment]
Great! The error has disappeared! Thanks for your help!
